services:
  douyin-download:
    image: kook00/tiktok-downloader

    container_name: douyin-download

    working_dir: /app
    command: ["uv", "run", "--no-sync", "main_webui.py"]
    restart: unless-stopped

    environment:
      TZ: America/Los_Angeles
      NVIDIA_VISIBLE_DEVICES: void

    ports:
      - "5555:5555"

    volumes:
      - ./settings:/app/settings
      - ./downloads:/app/downloads
