export const state = {
  token: "",
  logAfterId: 0,
  logCount: 0,
  ws: null,
  wsActive: false,
  wsConnecting: false,
  autoScroll: true,
  showDebugLogs: false,
  logRecords: [],
  fileEntries: [],
  fileSearch: "",
  filePage: 1,
  filePageSize: 24,
  filePages: 1,
  fileTotal: 0,
  fileSearchTimer: null,
  focusFilesAfterLoad: false,
  currentScope: "download",
  currentPath: "",
  currentParentPath: "",
  selectedFilePath: "",
  fileMasonryObserver: null,
  fileMasonryFrame: 0,
  fileLightboxIndex: -1,
  fileLightboxRestoreFocus: null,
  fileAccountContext: {
    platform: "",
    url: "",
    mark: "",
  },
  selectedTaskId: "",
  selectedTaskRenderKey: "",
  selectedTaskStatus: "",
  taskListLoading: false,
  taskListItems: [],
  taskListRenderKey: "",
  taskLastPollAt: 0,
  taskFilter: "all",
  taskSearch: "",
  taskAccountsLoading: false,
  taskAccounts: {
    page: 1,
    pageSize: 50,
    pages: 1,
    status: "",
    category: "",
  },
  taskAccountSelected: new Map(),
  taskAccountVisible: [],
  taskAccountArchive: {
    platform: "",
    items: [],
    restoreFocus: null,
    pending: false,
  },
  overviewLoading: false,
  overviewRefreshTimer: null,
  settingsData: {},
  collectorIdentities: [],
  collectMonitorItems: [],
  collectorPolicies: {},
  collectorAssignments: {
    douyin: [],
    tiktok: [],
  },
  collectorAssignmentsLoaded: {
    douyin: false,
    tiktok: false,
  },
  collectorAssignmentsLoading: {
    douyin: false,
    tiktok: false,
  },
  collectorAssignmentPagination: {
    douyin: { page: 1, pageSize: 50, pages: 1, total: 0, search: "", requestId: 0 },
    tiktok: { page: 1, pageSize: 50, pages: 1, total: 0, search: "", requestId: 0 },
  },
  collectorAssignmentRequests: {
    douyin: null,
    tiktok: null,
  },
  collectorAssignmentSearchTimer: null,
  collectorListLoading: false,
  collectorDialogRestoreFocus: null,
  collectorLoginBrowser: {
    identityId: "",
    sessionId: "",
    expiresAt: "",
    rfb: null,
    countdownTimer: null,
    restoreFocus: null,
    connecting: false,
  },
  accountRows: {
    douyin: [],
    tiktok: [],
  },
  deletedRows: {
    douyin: [],
    tiktok: [],
  },
  deletedPurge: {
    platform: "",
    mode: "",
    restoreFocus: null,
  },
  accountPagination: {
    active: {
      douyin: { page: 1, pageSize: 25 },
      tiktok: { page: 1, pageSize: 25 },
    },
    deleted: {
      douyin: { page: 1, pageSize: 15 },
      tiktok: { page: 1, pageSize: 15 },
    },
  },
  rawSettingsSource: {},
  rawSettingsSecretsIncluded: false,
  activeTab: "workbench",
  selectionAnchors: {
    active: {
      douyin: null,
      tiktok: null,
    },
    deleted: {
      douyin: null,
      tiktok: null,
    },
  },
  accountBoard: {
    platform: "douyin",
    page: 1,
    pageSize: 24,
    pages: 1,
    total: 0,
    unfilteredTotal: 0,
    columns: 4,
    refreshKind: "auto",
    viewMode: "avatar",
    search: "",
    status: "all",
    sort: "configured",
    searchTimer: null,
    restoreScrollY: null,
  },
  accountGallery: {
    platform: "douyin",
    url: "",
    mark: "",
    folderPath: "",
    folderFound: false,
    kind: "all",
    page: 1,
    pageSize: 24,
    pages: 1,
    total: 0,
    imageTotal: 0,
    videoTotal: 0,
    truncated: false,
    indexLimit: 10000,
    items: [],
    selectedIndex: -1,
    loading: false,
    requestId: 0,
    restoreFocus: null,
    positions: {},
  },
  accountBoardDirty: true,
  boardAvatarBatchRunning: false,
};
